id = "azutiku-theme"
name = "Azutiku Theme"
version = "0.1.0"
schema_version = 1
authors = ["Bas Wind <mailtobwind@gmail.com>"]
description = "A dark theme for Zed with a gentle, soft palette that's easy on the eyes."
repository = "https://github.com/bwind/zed-azutiku-theme"
